### ISSUE TITLE
[Action Required] Upgrade your App Engine Standard applications to Go 1.11 or 1.12 before October 1, 2019

### ISSUE THREAD

**Issue by tamalsaha** [GoogleCloudPlatform/govanityurls#29]
Today, I received an email like this. 

![Action-Required-Upgrade-your-App-Engine-Standard-applications-to-Go-1-11-or-1-12-before-October-1-2019-tamal-appscode-com-AppsCode-Inc-Mail](https://user-images.githubusercontent.com/94814/60283505-2694b980-98be-11e9-87c1-2a68c820bb91.png)

Does anyone know what things I need to update?

cc: @rakyll

**Comment by rakyll** [comment]
cc @broady @zombiezen

**Comment by zombiezen** [comment]
Redeploying the app to Go 1.11 should work without change. If you want to use Go 1.12, then you may have to tweak main.go to load your file without giving a command-line argument, but it should still largely work.

**Comment by tamalsaha** [comment]
@zombiezen , I tried to change the app.yaml to this.

```yaml
runtime: go111

handlers:
- url: /.*
  script: _go_app
```

I get this error: `File upload done.
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/.*' must be set to 'auto' for runtime go111.`

https://cloud.google.com/appengine/docs/standard/go111/go-differences page seem to recommend some additional changes.

**Comment by davidnewhall** [comment]
Change `script:` to `auto` instead of `_go_app` and it seems to work fine on go112.

**Comment by philips** [comment]
@davidnewhall I think I addressed all of these in https://github.com/GoogleCloudPlatform/govanityurls/pull/34

**Comment by davidnewhall** [comment]
I don't think this project is getting more updates. You're probably best off forking or picking one of the up to date forks that already exist. I forked and went hard core with the changes. See here https://github.com/golift/turbovanityurls. Good luck!

**Comment by rakyll** [comment]
Closed via #34.

(Note: I added some more contributors including @philips to the repo.)

**Comment by davidnewhall** [comment]
Sweet!
