### ISSUE TITLE
http (non-https) urls still redirecting to godoc.org

### ISSUE THREAD

**Issue by dnephin** [GoogleCloudPlatform/govanityurls#36]
Recently [I pulled in the changes](https://github.com/gotestyourself/vanityurl/commit/86589d428e16dd3c1c08d7166c51406677cdf94a) from  #33 and #34.

`https` urls (ex: https://gotest.tools/) redirect properly to https://pkg.go.dev/
However `http` urls (ex http://gotest.tools/) continue to redirect to https://godoc.org

[I attempted to set secure: always](https://github.com/gotestyourself/vanityurl/commit/7d96c4d8e4390c625bf358526e7281f84f79b83a) in the `app.yaml`, but that has not fixed the problem.

I confirmed in the appengine logs that the requests to `http` are going to the same service and version. No instances of older versions are running. The main difference in the logs seems to be that `https` requests get a 204 response code, and the `http` requests get a 200 response code.

I was previously already running with `runtime: go112`, but I may not have noticed the requests being handled incorrectly because nothing else had changed in the application.

Do you know if the upgrade to go1.12 runtime may be causing this problem, or how else I might be able to debug? I tried looking around stackoverflow but found nothing relevant.

I understand this issue may be an appengine bug, and not related to this project, but I thought I would ask here in case someone else using this project had the same problem.

**Comment by rakyll** [comment]
I can't reproduce this :( 

http://gotest.tools goes to https://pkg.go.dev/gotest.tools/?tab=doc but https://godoc.org/gotest.tools/assert errors with "Error getting package files from api.github.com.". Could it be a godoc.org issue?

**Comment by dnephin** [comment]
Oh, cool, http://gotest.tools is working now! Maybe the old pages were cached somewhere yesterday for a few hours.

The https://godoc.org/gotest.tools/assert error was the original problem I was trying to work around. godoc doesn't understanding package paths when there is a module version in them.

Thanks for taking a look! Seems resolved now.
